services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/:/src
    networks:
      - tripadvancer_net

networks:
  tripadvancer_net:
    external: true
    